services:
  bia:
    platform: linux/amd64
    image: 305068201474.dkr.ecr.us-east-1.amazonaws.com/ecr-bia:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BIA_API_URL: http://bia-dev-web.us-east-1.elasticbeanstalk.com 
    ports:
      - 80:8080
